### ISSUE TITLE
Publish version to Galaxy?

### ISSUE THREAD

**Issue by decentral1se** [IbrahimMohammad/ansible-role-mysql_secure_installation#1]
Hey, thanks for this solid role! Like https://galaxy.ansible.com/geerlingguy/mysql, I would like to have a version, which I can pin against in my `requirements.yml` going forward relying on this role. Something like:

```yaml
- src: IbrahimMohammad.mysql_secure_installation
  version: 1.0.0
```

Would it be possible?

**Comment by IbrahimMohammad** [comment]
Hi,
Sure, version added.
